<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Shaskia Aprillia Putri">
<meta name="dcterms.date" content="2022-08-10">

<title>Pengaruh Nilai Ekspor terhadap Pertumbuhan Ekonomi di Indonesia pada tahun 2017-2022</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Pengaruh Nilai Ekspor terhadap Pertumbuhan Ekonomi di Indonesia pada tahun 2017-2022</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Shaskia Aprillia Putri </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 10, 2022</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="poltekapp.jpg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">logo APP</figcaption>
</figure>
</div>
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar belakang</h3>
<p>Pertumbuhan ekonomi suatu negara merupakan indikator kritis yang mencerminkan kesehatan dan kinerja ekonominya. Menurut Sadono Sukirno (1996:33), pertumbuhan ekonomi adalah suatu proses kenaikan output perkapita yang terus menerus dalam jangka panjang. Produk Domestik Bruto (PDB) menjadi indikator utama dalam mengukur pertumbuhan ekonomi suatu negara. Sesuai dengan pendapat Rahardjo (2013) Pertumbuhan ekonomi merupakan upaya peningkatan kapasitas produksi untuk mencapai penambahan output, yang diukur menggunakan Produk Domestik Bruto (PDB) maupun menggunakan Produk Domestik Regional Bruto (PDRB) dalam suatu wilayah. Pertumbuhan PDB mencerminkan kinerja ekonomi secara keseluruhan berdasarkan berbagai sektor, termasuk ekspor.</p>
<p>Dalam konteks globalisasi ekonomi, ekspor menjadi kendaraan utama bagi negara-negara untuk memasuki pasar dunia, meningkatkan daya saing, dan mengoptimalkan sumber daya ekonominya. Sebagai sebuah negara berkembang, Indonesia telah mengimplementasikan kebijakan yang mendukung ekspor sebagai salah satu upaya untuk memperkuat pertumbuhan ekonominya. Dengan mengekspor beragam produk, mulai dari barang hingga jasa tingkat tinggi, suatu negara dapat memperluas pangsa pasar dan meningkatkan pertumbuhan ekonomi negaranya. Oleh karena itu, penelitian ini bertujuan untuk menggali lebih dalam mengenai pengaruh antara ekspor dan pertumbuhan ekonomi di Indonesia pada tahun 2017-2022.</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang lingkup</h3>
<p>Ruang lingkup pembahasan masalah disesuaikan dengan variabel yang akan dianalisis dalam penelitian ini, yang mencakup aspek mengenai data jumlah eskpor pada tahun 2017-2022 terhadap pertumbuhan ekonomi Indonesia. Data inilah yang akan menjadi bahan penelitian yang akan digunakan dalam proses analisis.</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan masalah</h3>
<ol type="1">
<li>Apakah adanya pengaruh pada nilai ekspor terhadap pertumbuhan ekonomi Indonesia?</li>
<li>Bagaimana hubungan antara nilai eksporterhadap pertumbuhan ekonomi Indonesia?</li>
</ol>
</section>
<section id="tujuan-dan-manfaat-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-dan-manfaat-penelitian"><span class="header-section-number">1.4</span> Tujuan dan manfaat penelitian</h3>
<p>Tujuan utama penelitian ini adalah untuk menyelidiki apakah terdapat pengaruh yang signifikan antara nilai ekspor dan pertumbuhan ekonomi di Indonesia pada periode tahun 2017-2022. Dengan demikian, penelitian ini bertujuan untuk memberikan wawasan lebih mendalam mengenai kontribusi nilai ekspor terhadap perkembangan ekonomi negara.Adapun manfaat dari penelitian ini yaitu dapat memberikan pandangan yang lebih akurat mengenai sejauh mana nilai ekspor berpengaruh terhadap pertumbuhan ekonomi di Indonesia.</p>
</section>
<section id="package" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="package"><span class="header-section-number">1.5</span> Package</h3>
<p>Packages yang digunakan antara lain sebagai berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(WDI) <span class="co"># tambahkan library lain jika diperlukan</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi pustaka</h2>
<ol type="1">
<li><p>Ekspor Ekspor memiliki peran penting dalam perekonomian suatu negara karena dapat meningkatkan pendapatan, menciptakan lapangan kerja, dan memperkuat pertumbuhan ekonomi. Menurut H Banu Santoso (2003), Ekspor adalah perdagangan dengan cara mengeluarkan barang dari dalam keluar wilayah pabean Indonesia dengan berdasarkan ketentuan yang berlaku.Negara-negara biasanya melakukan ekspor untuk memanfaatkan keunggulan komparatif yang dimilikinya dan memenuhi kebutuhan pasar internasional.</p></li>
<li><p>Pertumbuhan Ekonomi Pertumbuhan ekonomi merujuk pada peningkatan secara berkelanjutan dari jumlah barang dan jasa yang dihasilkan oleh suatu perekonomian dalam suatu periode waktu tertentu. Pertumbuhan ini umumnya diukur dengan perubahan Produk Domestik Bruto (PDB) suatu negara. PDB mengukur nilai total barang dan jasa yang dihasilkan dalam batas wilayah suatu negara dalam satu periode waktu, biasanya dalam satu tahun.Simon Kuznets (dalam Arsyad, 2010) menyatakan bahwa pertumbuhan ekonomi merupakan kenaikan kapasitas jangka panjang dari negara yang bersangkutan untuk menyediakan berbagai barang ekonomi kepada penduduknya.</p></li>
</ol>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode penelitian</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<table class="table">
<thead>
<tr class="header">
<th>Tahun</th>
<th>Ekspor</th>
<th>GDP</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2017</td>
<td>204924485909.911</td>
<td>1015618744159.73</td>
</tr>
<tr class="even">
<td>2018</td>
<td>218905647884.814</td>
<td>1042271532988.63</td>
</tr>
<tr class="odd">
<td>2019</td>
<td>208057763662.383</td>
<td>1119099871350.2</td>
</tr>
<tr class="even">
<td>2020</td>
<td>183546577015.846</td>
<td>1059054842698.48</td>
</tr>
<tr class="odd">
<td>2021</td>
<td>254008548673.178</td>
<td>1186505455736.54</td>
</tr>
<tr class="even">
<td>2022</td>
<td>323079953659.956</td>
<td>1319100220407.72</td>
</tr>
</tbody>
</table>
<p>Penelitian ini menggunakan data sekunder dengan bentuk data time series 2017-2022, data yang dipakai ialah data yang telah diolah dengan sumber World Development Indicators.</p>
<p>Membaca Data</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#import dataset</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">'Data Ekspor dan GDP Indonesia.xlsx'</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  Tahun             X       Y
  &lt;dbl&gt;         &lt;dbl&gt;   &lt;dbl&gt;
1  2017 204924485910. 1.02e12
2  2018 218905647885. 1.04e12
3  2019 208057763662. 1.12e12
4  2020 183546577016. 1.06e12
5  2021 254008548673. 1.19e12
6  2022 323079953660. 1.32e12</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> dat,<span class="fu">aes</span>(<span class="at">x=</span>X,<span class="at">y=</span>Y))<span class="sc">+</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>#| label: fig-mpg #| fig-cap: “City and highway mileage for 38 popular models of cars.Color by number of cylinders”</p>
<pre><code>
### Metode analisis

Metode yang dipilih adalah regresi univariat atau Ordinary Least Square (OLS) dengan 1 variabel independen. Penelitian ini bermaksud mencari hubungan antara nilai ekspor dan pertumbuhan ekonomi. Spesifikasi yang dilakukan adalah:

$$
y_{t}=\beta_0 + \beta_1 x_t+\mu_t
$$ di mana $y_t$ adalah pertumbuhan ekonomi dan $x_t$ adalah nilai ekspor.

## Pembahasan

### Pembahasan masalah
::: {.cell}

:::
::: {.cell}

```{.r .cell-code}
#import dataset
library(readxl)
dat&lt;-read_excel('Data Ekspor dan GDP Indonesia.xlsx')
head(dat)</code></pre>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  Tahun             X       Y
  &lt;dbl&gt;         &lt;dbl&gt;   &lt;dbl&gt;
1  2017 204924485910. 1.02e12
2  2018 218905647885. 1.04e12
3  2019 208057763662. 1.12e12
4  2020 183546577016. 1.06e12
5  2021 254008548673. 1.19e12
6  2022 323079953660. 1.32e12</code></pre>
</div>
<p>:::</p>
</section>
<section id="analisis-masalah" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">3.2</span> Analisis masalah</h3>
<p>Hasil regresinya adalah</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>reg<span class="ot">&lt;-</span><span class="fu">lm</span>(X<span class="sc">~</span>Y,<span class="at">data=</span>dat)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = X ~ Y, data = dat)

Residuals:
         1          2          3          4          5          6 
 1.697e+10  2.006e+10 -2.219e+10 -2.216e+10 -3.782e+09  1.110e+10 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept) -2.271e+11  9.444e+10  -2.404  0.07400 . 
Y            4.087e-01  8.370e-02   4.883  0.00815 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.128e+10 on 4 degrees of freedom
Multiple R-squared:  0.8563,    Adjusted R-squared:  0.8204 
F-statistic: 23.84 on 1 and 4 DF,  p-value: 0.008145</code></pre>
</div>
</div>
<p>Berdasarkan hasil analisis regresi linear yang dilakukan dengan rumusan model: X = -2.271 X 10^11 + 0.409 x Y</p>
<p>dengan X sebagai pertumbuhan ekonomi dan Y sebagai nilai ekspor, diperoleh beberapa informasi penting: 1. Intercept (Intersep): Koefisien intercept(-2.271 X 10^11) tidak signifikan pada tingkat kepercayaan 95%, dengan nilai p-value sebesar 0.07400. 2. Koefisien Y (Ekspor): Koefisien untuk Y (0.409) signifikan pada tingkat kepercayaan 95%, dengan nilai p-value sebesar 0.00815. 3. R-squared: Nilai R-squared sebesar 0.8563, yang mengindikasikan bahwa model dapat menjelaskan sekitar 85.63% variabilitas pertumbuhan ekonomi.</p>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">4</span> Kesimpulan</h2>
<ol type="1">
<li>Pengaruh Ekspor terhadap Pertumbuhan Ekonomi: Terdapat pengaruh yang signifikan antara nilai ekspor (Y)dan pertumbuhan ekonomi (X) Seiring dengan nilai koefisien (Y) yang signifikan positif. Artinya, peningkatan nilai ekspor berkontribusi positif terhadap pertumbuhan ekonomi Indonesia.</li>
<li>Hubungan Antara Nilai Ekspor dan Pertumbuhan Ekonomi: Hubungan antara nilai ekspor dan pertumbuhan ekonomi bersifat positif, yang dapat diartikan bahwa semakin tinggi nilai ekspor, semakin besar kontribusinya terhadap pertumbuhan ekonomi Indonesia</li>
</ol>
</section>
<section id="referensi" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="referensi"><span class="header-section-number">5</span> Referensi</h2>
<p>Agustina, S., Astuti, A., Kusumawati, A. C., Rohma, S. M., Aini, N., Oktaviani, D., … &amp; Tambunan, N. (2023). PENGARUH EKSPOR TERHADAP PERTUMBUHAN EKONOMI DI INDONESIA. Jurnal Manajemen dan Ekonomi Kreatif, 1(1), 113-126.</p>
<p>Siregar, I. M., Pratiwi, I., Nurhasanah, N., &amp; Sinaga, S. (2019). Pengaruh ekspor terhadap pertumbuhan ekonomi di Indonesia periode tahun 2013-2017. Jurnal Ekodik: Ekonomi Pendidikan, 7(2), 46-54.</p>
<p>Hodijah, S., &amp; Angelina, G. P. (2021). Analisis pengaruh ekspor dan impor terhadap pertumbuhan ekonomi di Indonesia. Jurnal Manajemen Terapan Dan Keuangan, 10(01), 53-62.</p>
<p>Hanifah, U. (2022). Pengaruh Ekspor Dan Impor Terhadap Pertumbuhan Ekonomi Di Indonesia. Transekonomika: Akuntansi, Bisnis Dan Keuangan, 2(6), 107-126.</p>
<p>Astuti, I. P., &amp; Ayuningtyas, F. J. (2018). Pengaruh ekspor dan impor terhadap pertumbuhan ekonomi di Indonesia. Jurnal Ekonomi &amp; Studi Pembangunan, 19(1), 1-10.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>